# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrea/cernbox/doctoral/miniPET/hybrid_pixel/g4hybrid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrea/cernbox/doctoral/miniPET/hybrid_pixel/g4hybrid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/cernbox/doctoral/miniPET/hybrid_pixel/g4hybrid/CMakeFiles /home/andrea/cernbox/doctoral/miniPET/hybrid_pixel/g4hybrid/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/cernbox/doctoral/miniPET/hybrid_pixel/g4hybrid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named g4hybrid

# Build rule for target.
g4hybrid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g4hybrid
.PHONY : g4hybrid

# fast build rule for target.
g4hybrid/fast:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/build
.PHONY : g4hybrid/fast

g4hybrid.o: g4hybrid.cc.o

.PHONY : g4hybrid.o

# target to build an object file
g4hybrid.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/g4hybrid.cc.o
.PHONY : g4hybrid.cc.o

g4hybrid.i: g4hybrid.cc.i

.PHONY : g4hybrid.i

# target to preprocess a source file
g4hybrid.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/g4hybrid.cc.i
.PHONY : g4hybrid.cc.i

g4hybrid.s: g4hybrid.cc.s

.PHONY : g4hybrid.s

# target to generate assembly for a file
g4hybrid.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/g4hybrid.cc.s
.PHONY : g4hybrid.cc.s

src/ConfigFile.o: src/ConfigFile.cc.o

.PHONY : src/ConfigFile.o

# target to build an object file
src/ConfigFile.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/ConfigFile.cc.o
.PHONY : src/ConfigFile.cc.o

src/ConfigFile.i: src/ConfigFile.cc.i

.PHONY : src/ConfigFile.i

# target to preprocess a source file
src/ConfigFile.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/ConfigFile.cc.i
.PHONY : src/ConfigFile.cc.i

src/ConfigFile.s: src/ConfigFile.cc.s

.PHONY : src/ConfigFile.s

# target to generate assembly for a file
src/ConfigFile.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/ConfigFile.cc.s
.PHONY : src/ConfigFile.cc.s

src/CreateTree.o: src/CreateTree.cc.o

.PHONY : src/CreateTree.o

# target to build an object file
src/CreateTree.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/CreateTree.cc.o
.PHONY : src/CreateTree.cc.o

src/CreateTree.i: src/CreateTree.cc.i

.PHONY : src/CreateTree.i

# target to preprocess a source file
src/CreateTree.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/CreateTree.cc.i
.PHONY : src/CreateTree.cc.i

src/CreateTree.s: src/CreateTree.cc.s

.PHONY : src/CreateTree.s

# target to generate assembly for a file
src/CreateTree.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/CreateTree.cc.s
.PHONY : src/CreateTree.cc.s

src/MyMaterials.o: src/MyMaterials.cc.o

.PHONY : src/MyMaterials.o

# target to build an object file
src/MyMaterials.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/MyMaterials.cc.o
.PHONY : src/MyMaterials.cc.o

src/MyMaterials.i: src/MyMaterials.cc.i

.PHONY : src/MyMaterials.i

# target to preprocess a source file
src/MyMaterials.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/MyMaterials.cc.i
.PHONY : src/MyMaterials.cc.i

src/MyMaterials.s: src/MyMaterials.cc.s

.PHONY : src/MyMaterials.s

# target to generate assembly for a file
src/MyMaterials.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/MyMaterials.cc.s
.PHONY : src/MyMaterials.cc.s

src/g4matrixActionInitialization.o: src/g4matrixActionInitialization.cc.o

.PHONY : src/g4matrixActionInitialization.o

# target to build an object file
src/g4matrixActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixActionInitialization.cc.o
.PHONY : src/g4matrixActionInitialization.cc.o

src/g4matrixActionInitialization.i: src/g4matrixActionInitialization.cc.i

.PHONY : src/g4matrixActionInitialization.i

# target to preprocess a source file
src/g4matrixActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixActionInitialization.cc.i
.PHONY : src/g4matrixActionInitialization.cc.i

src/g4matrixActionInitialization.s: src/g4matrixActionInitialization.cc.s

.PHONY : src/g4matrixActionInitialization.s

# target to generate assembly for a file
src/g4matrixActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixActionInitialization.cc.s
.PHONY : src/g4matrixActionInitialization.cc.s

src/g4matrixDetectorConstruction.o: src/g4matrixDetectorConstruction.cc.o

.PHONY : src/g4matrixDetectorConstruction.o

# target to build an object file
src/g4matrixDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixDetectorConstruction.cc.o
.PHONY : src/g4matrixDetectorConstruction.cc.o

src/g4matrixDetectorConstruction.i: src/g4matrixDetectorConstruction.cc.i

.PHONY : src/g4matrixDetectorConstruction.i

# target to preprocess a source file
src/g4matrixDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixDetectorConstruction.cc.i
.PHONY : src/g4matrixDetectorConstruction.cc.i

src/g4matrixDetectorConstruction.s: src/g4matrixDetectorConstruction.cc.s

.PHONY : src/g4matrixDetectorConstruction.s

# target to generate assembly for a file
src/g4matrixDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixDetectorConstruction.cc.s
.PHONY : src/g4matrixDetectorConstruction.cc.s

src/g4matrixEventAction.o: src/g4matrixEventAction.cc.o

.PHONY : src/g4matrixEventAction.o

# target to build an object file
src/g4matrixEventAction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixEventAction.cc.o
.PHONY : src/g4matrixEventAction.cc.o

src/g4matrixEventAction.i: src/g4matrixEventAction.cc.i

.PHONY : src/g4matrixEventAction.i

# target to preprocess a source file
src/g4matrixEventAction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixEventAction.cc.i
.PHONY : src/g4matrixEventAction.cc.i

src/g4matrixEventAction.s: src/g4matrixEventAction.cc.s

.PHONY : src/g4matrixEventAction.s

# target to generate assembly for a file
src/g4matrixEventAction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixEventAction.cc.s
.PHONY : src/g4matrixEventAction.cc.s

src/g4matrixPhysicsList.o: src/g4matrixPhysicsList.cc.o

.PHONY : src/g4matrixPhysicsList.o

# target to build an object file
src/g4matrixPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPhysicsList.cc.o
.PHONY : src/g4matrixPhysicsList.cc.o

src/g4matrixPhysicsList.i: src/g4matrixPhysicsList.cc.i

.PHONY : src/g4matrixPhysicsList.i

# target to preprocess a source file
src/g4matrixPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPhysicsList.cc.i
.PHONY : src/g4matrixPhysicsList.cc.i

src/g4matrixPhysicsList.s: src/g4matrixPhysicsList.cc.s

.PHONY : src/g4matrixPhysicsList.s

# target to generate assembly for a file
src/g4matrixPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPhysicsList.cc.s
.PHONY : src/g4matrixPhysicsList.cc.s

src/g4matrixPrimaryGeneratorAction.o: src/g4matrixPrimaryGeneratorAction.cc.o

.PHONY : src/g4matrixPrimaryGeneratorAction.o

# target to build an object file
src/g4matrixPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPrimaryGeneratorAction.cc.o
.PHONY : src/g4matrixPrimaryGeneratorAction.cc.o

src/g4matrixPrimaryGeneratorAction.i: src/g4matrixPrimaryGeneratorAction.cc.i

.PHONY : src/g4matrixPrimaryGeneratorAction.i

# target to preprocess a source file
src/g4matrixPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPrimaryGeneratorAction.cc.i
.PHONY : src/g4matrixPrimaryGeneratorAction.cc.i

src/g4matrixPrimaryGeneratorAction.s: src/g4matrixPrimaryGeneratorAction.cc.s

.PHONY : src/g4matrixPrimaryGeneratorAction.s

# target to generate assembly for a file
src/g4matrixPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixPrimaryGeneratorAction.cc.s
.PHONY : src/g4matrixPrimaryGeneratorAction.cc.s

src/g4matrixRunAction.o: src/g4matrixRunAction.cc.o

.PHONY : src/g4matrixRunAction.o

# target to build an object file
src/g4matrixRunAction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixRunAction.cc.o
.PHONY : src/g4matrixRunAction.cc.o

src/g4matrixRunAction.i: src/g4matrixRunAction.cc.i

.PHONY : src/g4matrixRunAction.i

# target to preprocess a source file
src/g4matrixRunAction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixRunAction.cc.i
.PHONY : src/g4matrixRunAction.cc.i

src/g4matrixRunAction.s: src/g4matrixRunAction.cc.s

.PHONY : src/g4matrixRunAction.s

# target to generate assembly for a file
src/g4matrixRunAction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixRunAction.cc.s
.PHONY : src/g4matrixRunAction.cc.s

src/g4matrixStackingAction.o: src/g4matrixStackingAction.cc.o

.PHONY : src/g4matrixStackingAction.o

# target to build an object file
src/g4matrixStackingAction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixStackingAction.cc.o
.PHONY : src/g4matrixStackingAction.cc.o

src/g4matrixStackingAction.i: src/g4matrixStackingAction.cc.i

.PHONY : src/g4matrixStackingAction.i

# target to preprocess a source file
src/g4matrixStackingAction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixStackingAction.cc.i
.PHONY : src/g4matrixStackingAction.cc.i

src/g4matrixStackingAction.s: src/g4matrixStackingAction.cc.s

.PHONY : src/g4matrixStackingAction.s

# target to generate assembly for a file
src/g4matrixStackingAction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixStackingAction.cc.s
.PHONY : src/g4matrixStackingAction.cc.s

src/g4matrixSteppingAction.o: src/g4matrixSteppingAction.cc.o

.PHONY : src/g4matrixSteppingAction.o

# target to build an object file
src/g4matrixSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingAction.cc.o
.PHONY : src/g4matrixSteppingAction.cc.o

src/g4matrixSteppingAction.i: src/g4matrixSteppingAction.cc.i

.PHONY : src/g4matrixSteppingAction.i

# target to preprocess a source file
src/g4matrixSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingAction.cc.i
.PHONY : src/g4matrixSteppingAction.cc.i

src/g4matrixSteppingAction.s: src/g4matrixSteppingAction.cc.s

.PHONY : src/g4matrixSteppingAction.s

# target to generate assembly for a file
src/g4matrixSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingAction.cc.s
.PHONY : src/g4matrixSteppingAction.cc.s

src/g4matrixSteppingVerbose.o: src/g4matrixSteppingVerbose.cc.o

.PHONY : src/g4matrixSteppingVerbose.o

# target to build an object file
src/g4matrixSteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingVerbose.cc.o
.PHONY : src/g4matrixSteppingVerbose.cc.o

src/g4matrixSteppingVerbose.i: src/g4matrixSteppingVerbose.cc.i

.PHONY : src/g4matrixSteppingVerbose.i

# target to preprocess a source file
src/g4matrixSteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingVerbose.cc.i
.PHONY : src/g4matrixSteppingVerbose.cc.i

src/g4matrixSteppingVerbose.s: src/g4matrixSteppingVerbose.cc.s

.PHONY : src/g4matrixSteppingVerbose.s

# target to generate assembly for a file
src/g4matrixSteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/g4hybrid.dir/build.make CMakeFiles/g4hybrid.dir/src/g4matrixSteppingVerbose.cc.s
.PHONY : src/g4matrixSteppingVerbose.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... g4hybrid"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... g4hybrid.o"
	@echo "... g4hybrid.i"
	@echo "... g4hybrid.s"
	@echo "... src/ConfigFile.o"
	@echo "... src/ConfigFile.i"
	@echo "... src/ConfigFile.s"
	@echo "... src/CreateTree.o"
	@echo "... src/CreateTree.i"
	@echo "... src/CreateTree.s"
	@echo "... src/MyMaterials.o"
	@echo "... src/MyMaterials.i"
	@echo "... src/MyMaterials.s"
	@echo "... src/g4matrixActionInitialization.o"
	@echo "... src/g4matrixActionInitialization.i"
	@echo "... src/g4matrixActionInitialization.s"
	@echo "... src/g4matrixDetectorConstruction.o"
	@echo "... src/g4matrixDetectorConstruction.i"
	@echo "... src/g4matrixDetectorConstruction.s"
	@echo "... src/g4matrixEventAction.o"
	@echo "... src/g4matrixEventAction.i"
	@echo "... src/g4matrixEventAction.s"
	@echo "... src/g4matrixPhysicsList.o"
	@echo "... src/g4matrixPhysicsList.i"
	@echo "... src/g4matrixPhysicsList.s"
	@echo "... src/g4matrixPrimaryGeneratorAction.o"
	@echo "... src/g4matrixPrimaryGeneratorAction.i"
	@echo "... src/g4matrixPrimaryGeneratorAction.s"
	@echo "... src/g4matrixRunAction.o"
	@echo "... src/g4matrixRunAction.i"
	@echo "... src/g4matrixRunAction.s"
	@echo "... src/g4matrixStackingAction.o"
	@echo "... src/g4matrixStackingAction.i"
	@echo "... src/g4matrixStackingAction.s"
	@echo "... src/g4matrixSteppingAction.o"
	@echo "... src/g4matrixSteppingAction.i"
	@echo "... src/g4matrixSteppingAction.s"
	@echo "... src/g4matrixSteppingVerbose.o"
	@echo "... src/g4matrixSteppingVerbose.i"
	@echo "... src/g4matrixSteppingVerbose.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

